/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conferenceproject;

import static conferenceproject.JFrameMain.confNow;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import dao.*;
import java.io.File;
import static java.lang.Integer.parseInt;
import java.util.Date;
import javax.swing.JOptionPane;
import pojos.Destination;
import static conferenceproject.JDialogLogin.usernow;
import java.util.List;
import pojos.*;

/**
 *
 * @author LONG LIN
 */
public class JDialoInfoConf extends javax.swing.JDialog {

    private UserConferenceDao userConD = new UserConferenceDao();
    public static int checkin = 0;

    public static List<Conference> conUpdate;

    private conferenceDao conD = new conferenceDao();
    private destinationDao desD = new destinationDao();
    User pa = usernow;

    /**
     * Creates new form JDialoInfoConf
     */
    public JDialoInfoConf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jButtonGo.setVisible(true);
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);

//        System.out.println(pa);
        //nếu không là user loại 1 hay admin sẽ ko được chỉnh sửa 
        if (pa == null || pa.getType() != 1) {
            this.jButtonUpdate.setVisible(false);
        }
        if (pa != null) {
            if (pa.getType() == 3) {
                System.out.println("hello");
                this.jButtonGo.setVisible(false);
            }
        }

        this.setLocationRelativeTo(null);
        Image image = null;
        int check = 0;
        do {
            try {
                if (check == 1) {
                    File sourceimage = new File("src\\img\\error.jpg");
                    image = ImageIO.read(sourceimage);
                    check = 2;
                    break;
                }

                URL url = new URL(confNow.getImg());
                image = ImageIO.read(url);
                break;

//                URL url = new URL(confNow.getImg().toString());
//                HttpURLConnection huc = (HttpURLConnection) url.openConnection();
//                int responseCode = huc.getResponseCode();
//                if (responseCode == 200) {
//                    image = ImageIO.read(url);
//                } 
            } catch (IOException e) {
                check = 1;
                System.out.println(e);
            }
        } while (check != 2);

        //resize image
        image = image.getScaledInstance(600, 380, java.awt.Image.SCALE_SMOOTH);
        jLabel2.setIcon(new ImageIcon(image));
        this.idC.setText(confNow.getIdConference().toString());
        this.nameC.setText(confNow.getName());
        this.infoC.setText(confNow.getInfo());
        this.allInfoC.setText(confNow.getAllInfo());
        this.limitC.setText(confNow.getMax().toString());
        this.imgC.setText(confNow.getImg().toString());
//        this.dateC.setText(confNow.getDate().toString());
        this.jDateChooser.setDate(confNow.getDate());
        this.loC.setText(confNow.getDestination().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        idC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        limitC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        allInfoC = new javax.swing.JTextArea();
        nameC = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        infoC = new javax.swing.JTextField();
        imgC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        loC = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jButtonGo = new javax.swing.JButton();
        jButtonListGo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Tên:");

        idC.setEditable(false);
        idC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        idC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Thông tin chi tiết:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Số lượng:");

        limitC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        limitC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitCActionPerformed(evt);
            }
        });

        allInfoC.setColumns(20);
        allInfoC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        allInfoC.setLineWrap(true);
        allInfoC.setRows(5);
        allInfoC.setWrapStyleWord(true);
        jScrollPane2.setViewportView(allInfoC);

        nameC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nameC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Id:");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Thông tin:");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("Thời gian:");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("Hình ảnh:");

        infoC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        infoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoCActionPerformed(evt);
            }
        });

        imgC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        imgC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgCActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin chi tiết");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("Địa điểm:");

        loC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        loC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loCActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(250, 99, 12));
        jButtonUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(java.awt.Color.white);
        jButtonUpdate.setText("Sửa");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jDateChooser.setDateFormatString("yyyy-MM-dd");
        jDateChooser.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jButtonGo.setBackground(new java.awt.Color(250, 99, 12));
        jButtonGo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonGo.setForeground(java.awt.Color.white);
        jButtonGo.setText("Tham gia");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        jButtonListGo.setBackground(new java.awt.Color(250, 99, 12));
        jButtonListGo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonListGo.setForeground(java.awt.Color.white);
        jButtonListGo.setText("Danh sách tham gia");
        jButtonListGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListGoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số lượng đăng ký đã được duyệt đã đầy");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đã hết hạn đăng ký tham gia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel21))))
                                    .addComponent(jLabel14))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(limitC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                                    .addComponent(loC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                                    .addComponent(imgC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                                    .addComponent(infoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                                    .addComponent(nameC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                                    .addComponent(idC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonListGo)
                                .addGap(379, 379, 379)
                                .addComponent(jButtonGo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, Short.MAX_VALUE)
                                .addComponent(jButtonUpdate)))
                        .addGap(62, 62, 62)))
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(317, 317, 317)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(367, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nameC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel14)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imgC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limitC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListGo)
                    .addComponent(jButtonGo)
                    .addComponent(jButtonUpdate))
                .addGap(23, 23, 23))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(839, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(76, 76, 76)))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCActionPerformed

    private void limitCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitCActionPerformed

    private void nameCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCActionPerformed

    private void infoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoCActionPerformed

    private void imgCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgCActionPerformed

    private void loCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loCActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        Conference con = this.conD.find(this.idC.getText());
        con.setName(this.nameC.getText());
        con.setInfo(this.infoC.getText());
        con.setAllInfo(this.allInfoC.getText());
        con.setImg(this.imgC.getText());

        Destination d = new Destination();
        d = desD.findByName(this.loC.getText());
        con.setDestination(d);

        Date date = this.jDateChooser.getDate();
        con.setDate(date);
        con.setMax(parseInt(this.limitC.getText()));
        if (this.conD.update(con)) {
            JOptionPane.showMessageDialog(null, "Sửa hội nghị thành công! :)");
            conUpdate = conD.findAll();
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Sửa địa điểm thất bại");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);

        String idCon = this.idC.getText();
        List<UserConference> ls = this.userConD.findAll();
        int count = 0;
        for (UserConference con : ls) {
            //kiểm tra hội nghị có trùng tên với cái được chọn và trạng thái được duyệt mới được cộng 
            if (con.getConference().getIdConference().equals(parseInt(idCon)) && con.getState() == 1) {
                count++;
            }
        }
//            System.out.println(count);
//            System.out.println(confNow.getMax());
        Date date1 = new Date();
//            System.out.println(date1.toString());
        int check = confNow.getDate().compareTo(date1);
        System.out.println(check);
        if (check > 0) {
            if (count < confNow.getMax()) {
                if (usernow == null) {
                    checkin = 1;
                    JOptionPane.showMessageDialog(null, "Bạn phải đăng nhập trước khi đăng kí");
                    JDialogLogin f = new JDialogLogin(this.jFrame1, rootPaneCheckingEnabled);
                    f.setVisible(true);
                } else {
                    String idUser = usernow.getIdUser().toString();
                    if (this.userConD.save(idUser, idCon)) {
                        JOptionPane.showMessageDialog(null, "Đăng kí tham gia thành công");
                    } else {

                        JOptionPane.showMessageDialog(null, "Bạn đã đăng kí tham gia rồi!");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Số lượng đăng kí đã đầy");
                this.jLabel3.setVisible(true);
            }
        } else {
            this.jLabel4.setVisible(true);
            JOptionPane.showMessageDialog(null, "Duyệt tham gia thất bại. Vì đã quá hạn!");
        }
    }//GEN-LAST:event_jButtonGoActionPerformed

    private void jButtonListGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListGoActionPerformed
        JDialogListGo f = new JDialogListGo(this.jFrame1, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_jButtonListGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialoInfoConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialoInfoConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialoInfoConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialoInfoConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialoInfoConf dialog = new JDialoInfoConf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea allInfoC;
    private javax.swing.JTextField idC;
    private javax.swing.JTextField imgC;
    private javax.swing.JTextField infoC;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonListGo;
    private javax.swing.JButton jButtonUpdate;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField limitC;
    private javax.swing.JTextField loC;
    private javax.swing.JTextField nameC;
    // End of variables declaration//GEN-END:variables
}
