package pojos;
// Generated Jul 25, 2020 9:54:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conference generated by hbm2java
 */
@Entity
@Table(name="conference"
    ,catalog="conference_manager"
)
public class Conference  implements java.io.Serializable {


     private Integer idConference;
     private Destination destination;
     private String name;
     private String info;
     private String allInfo;
     private String img;
     private Date date;
     private Integer max;
     private Set<UserConference> userConferences = new HashSet<UserConference>(0);

    public Conference() {
    }

    public Conference(Destination destination, String name, String info, String allInfo, String img, Date date, Integer max, Set<UserConference> userConferences) {
       this.destination = destination;
       this.name = name;
       this.info = info;
       this.allInfo = allInfo;
       this.img = img;
       this.date = date;
       this.max = max;
       this.userConferences = userConferences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idConference", unique=true, nullable=false)
    public Integer getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(Integer idConference) {
        this.idConference = idConference;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDestination")
    public Destination getDestination() {
        return this.destination;
    }
    
    public void setDestination(Destination destination) {
        this.destination = destination;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="info", length=100)
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }

    
    @Column(name="allInfo", length=1000)
    public String getAllInfo() {
        return this.allInfo;
    }
    
    public void setAllInfo(String allInfo) {
        this.allInfo = allInfo;
    }

    
    @Column(name="img")
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="max")
    public Integer getMax() {
        return this.max;
    }
    
    public void setMax(Integer max) {
        this.max = max;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conference")
    public Set<UserConference> getUserConferences() {
        return this.userConferences;
    }
    
    public void setUserConferences(Set<UserConference> userConferences) {
        this.userConferences = userConferences;
    }




}


