package pojos;
// Generated Jul 25, 2020 9:54:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Destination generated by hbm2java
 */
@Entity
@Table(name="destination"
    ,catalog="conference_manager"
)
public class Destination  implements java.io.Serializable {


     private Integer idDestination;
     private String name;
     private String address;
     private Integer size;
     private Set<Conference> conferences = new HashSet<Conference>(0);

    public Destination() {
    }

    public Destination(String name, String address, Integer size, Set<Conference> conferences) {
       this.name = name;
       this.address = address;
       this.size = size;
       this.conferences = conferences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDestination", unique=true, nullable=false)
    public Integer getIdDestination() {
        return this.idDestination;
    }
    
    public void setIdDestination(Integer idDestination) {
        this.idDestination = idDestination;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="size")
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="destination")
    public Set<Conference> getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set<Conference> conferences) {
        this.conferences = conferences;
    }




}


