package pojos;
// Generated Jul 25, 2020 9:54:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserConferenceId generated by hbm2java
 */
@Embeddable
public class UserConferenceId  implements java.io.Serializable {


     private int idUser;
     private int idConference;

    public UserConferenceId() {
    }

    public UserConferenceId(int idUser, int idConference) {
       this.idUser = idUser;
       this.idConference = idConference;
    }
   


    @Column(name="idUser", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    @Column(name="idConference", nullable=false)
    public int getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(int idConference) {
        this.idConference = idConference;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserConferenceId) ) return false;
		 UserConferenceId castOther = ( UserConferenceId ) other; 
         
		 return (this.getIdUser()==castOther.getIdUser())
 && (this.getIdConference()==castOther.getIdConference());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUser();
         result = 37 * result + this.getIdConference();
         return result;
   }   


}


