package pojos;
// Generated Jul 25, 2020 9:54:21 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserConference generated by hbm2java
 */
@Entity
@Table(name="user_conference"
    ,catalog="conference_manager"
)
public class UserConference  implements java.io.Serializable {


     private UserConferenceId id;
     private Conference conference;
     private User user;
     private Integer state;

    public UserConference() {
    }

	
    public UserConference(UserConferenceId id, Conference conference, User user) {
        this.id = id;
        this.conference = conference;
        this.user = user;
    }
    public UserConference(UserConferenceId id, Conference conference, User user, Integer state) {
       this.id = id;
       this.conference = conference;
       this.user = user;
       this.state = state;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idUser", column=@Column(name="idUser", nullable=false) ), 
        @AttributeOverride(name="idConference", column=@Column(name="idConference", nullable=false) ) } )
    public UserConferenceId getId() {
        return this.id;
    }
    
    public void setId(UserConferenceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idConference", nullable=false, insertable=false, updatable=false)
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUser", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="state")
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }




}


